version: '3.7'
services:
    node:
        build: docker/node
        expose:
            - 5173
        ports:
            - '5173:5173'
        volumes:
            - './application:/application'
        tty: true
        stdin_open: true
        command: npm run dev

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './application:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9999:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - './application:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    redis:
        image: 'redis:alpine'

    db:
        image: 'biarms/mysql'
        working_dir: /application
        volumes:
            - './application:/application'
            - './data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=laravel
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
        ports:
            - '3306:3306'

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8888:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
